In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [ ]:
sales = pd.read_csv("sales.csv", sep=";")
sales.head()

Price  Advertising  Sales
0    2.0           53    478
1    2.5           52    373
2    3.0           50    335
3    2.0           55    473
4    2.5           53    358

In [ ]:
X = sales.iloc[:,1:2]
Y = sales.iloc[:,2]

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X,Y,test_size=0.2, random_state=0)

In [ ]:
from sklearn.neural_network import MLPRegressor

In [ ]:
nn_reg = MLPRegressor(random_state=1, max_iter=5000,hidden_layer_sizes=(1,2,3,4),activation='relu')

In [ ]:
nn_reg.fit(X_train, Y_train)

C:\Users\admin BASE\Anaconda31\lib\site-packages\sklearn\neural_network\multilayer_perceptron.py:566: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (5000) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)


MLPRegressor(activation='relu', alpha=0.0001, batch_size='auto', beta_1=0.9,
             beta_2=0.999, early_stopping=False, epsilon=1e-08,
             hidden_layer_sizes=(1, 2, 3, 4), learning_rate='constant',
             learning_rate_init=0.001, max_iter=5000, momentum=0.9,
             n_iter_no_change=10, nesterovs_momentum=True, power_t=0.5,
             random_state=1, shuffle=True, solver='adam', tol=0.0001,
             validation_fraction=0.1, verbose=False, warm_start=False)

In [ ]:
nn_reg.coefs_

[array([[-2.46748135e-82]]),
 array([[-1.71523909e-07,  1.46131600e-43]]),
 array([[-8.65560021e-029, -1.88642629e-073,  2.21195394e-092],
        [ 2.15784365e-113,  1.09375252e-101, -2.03019062e-063]]),
 array([[-3.97685242e-077,  1.30562277e-105,  6.71294722e-111,
          1.47874660e-031],
        [ 1.32411439e-043,  8.57898750e-044,  7.73086722e+000,
          3.33589565e-072],
        [-1.41403195e-070,  8.39851129e-028,  5.30645740e-025,
         -1.51132280e-022]]),
 array([[ 1.28744465e-101],
        [ 1.01615079e-013],
        [ 6.26645735e+000],
        [-2.13108128e-061]])]

In [ ]:
nn_reg.intercepts_

[array([0.76322643]),
 array([-0.99912522, -1.15304058]),
 array([-0.64751268,  7.68176845, -1.0354419 ]),
 array([-0.85350469, -0.61135527,  6.66320967, -0.74371715]),
 array([3.7353984])]

In [ ]:
y_hat=nn_reg.predict(X_test)

In [ ]:
from sklearn.metrics import mean_squared_error
mse = mean_squared_error(Y_test,y_hat)
mse

15643.749610648465

In [ ]:
import math
rmse=math.sqrt(mse)
rmse

125.07497595701734